### ISSUE TITLE
Overcommit support

### ISSUE THREAD

**Issue by carymrobbins** [scalastyle/scalastyle#162]
This is a sister ticket to https://github.com/brigade/overcommit/issues/282

The [documentation](http://www.scalastyle.org/git-pre-commit-hook.html) doesn't seem to explain _how_ to get this working properly.  Maybe I'm missing something obvious.

**Comment by matthewfarwell** [comment]
This has been fixed with https://github.com/scalastyle/scalastyle.github.com/pull/12

**Comment by carymrobbins** [comment]
@matthewfarwell - Thanks for this, but this requires a `scalastyle` executable to exist on your path.  I just wrote a script to handle it, but what's the standard way for this to work?

**Comment by carymrobbins** [comment]
Oh, also note that this is also an alternative - 

```yaml
PreCommit:
  Scalastyle:
    enabled: true
    command: java
    flags: ['-jar', 'path/to/scalastyle_2.10-0.6.0-batch.jar', '-c', 'scalastyle-config.xml']
```
